using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace RhMcp.Router.Codegen;

// Incremental source generator that scans plugin tool source files (passed as
// AdditionalFiles from the router project) and emits a router-side proxy class
// for each [McpServerTool] method. Generated proxies prepend a `slot` argument
// and forward the call to ProxyDispatcher.CallToolAsync.
//
// Parameter type rule: primitive types (string/bool/int/long/double/float and
// their nullables/arrays) pass through unchanged. Anything else — including
// Rhino-specific types like Vector3d and the plugin's record structs — maps to
// System.Text.Json.JsonElement? so the router doesn't have to reference
// RhinoCommon or duplicate types. The plugin deserialises on its end.
//
// Plugin tools take RhinoDoc as their first parameter (auto-injected from DI in
// the plugin's MCP server). That parameter is skipped in the proxy signature.
[Generator]
public class RouterToolGenerator : IIncrementalGenerator
{
    private static readonly HashSet<string> PassThroughTypes = new()
    {
        "string", "string?",
        "string[]", "string?[]", "string[]?", "string?[]?",
        "bool", "bool?",
        "int", "int?", "int[]",
        "long", "long?",
        "double", "double?",
        "float", "float?",
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var toolFiles = context.AdditionalTextsProvider
            .Where(static t => IsToolFile(t.Path));

        var parsed = toolFiles.Select(static (file, ct) =>
        {
            var text = file.GetText(ct);
            if (text is null) return default;
            var tree = CSharpSyntaxTree.ParseText(text, cancellationToken: ct);
            return new ParsedFile(file.Path, tree);
        }).Where(static p => p.Tree is not null);

        var tools = parsed.SelectMany(static (file, _) => ExtractTools(file.Tree!));

        context.RegisterSourceOutput(tools.Collect(), static (spc, all) =>
        {
            // Build a single combined file containing every proxy. Easier to debug than
            // 25 separate .g.cs files and avoids name-collision pitfalls.
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace RhMcp.Router.Tools.Generated;");
            sb.AppendLine();

            foreach (var tool in all)
            {
                EmitProxy(sb, tool);
                sb.AppendLine();
            }

            spc.AddSource("RouterToolProxies.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private readonly record struct ParsedFile(string Path, SyntaxTree? Tree);

    private static bool IsToolFile(string path)
    {
        var normalised = path.Replace('\\', '/');
        return normalised.EndsWith(".cs", System.StringComparison.Ordinal)
            && normalised.Contains("/rhino/Tools/");
    }

    private static IEnumerable<ToolInfo> ExtractTools(SyntaxTree tree)
    {
        foreach (var classDecl in tree.GetRoot().DescendantNodes().OfType<ClassDeclarationSyntax>())
        {
            if (!HasAttribute(classDecl.AttributeLists, "McpServerToolType")) continue;
            var className = classDecl.Identifier.ValueText;

            foreach (var method in classDecl.Members.OfType<MethodDeclarationSyntax>())
            {
                var toolAttr = FindAttribute(method.AttributeLists, "McpServerTool");
                if (toolAttr is null) continue;

                var toolName = ExtractStringArg(toolAttr, "Name");
                if (toolName is null) continue;

                var descAttr = FindAttribute(method.AttributeLists, "Description");
                var description = descAttr is null ? "" : ExtractStringArg(descAttr) ?? "";

                var parameters = new List<ParameterInfo>();
                foreach (var p in method.ParameterList.Parameters)
                {
                    var typeText = p.Type?.ToString() ?? "object";
                    // Skip the auto-injected RhinoDoc parameter — it's not part of the
                    // MCP arg surface, the plugin's SDK fills it from DI.
                    if (typeText == "RhinoDoc") continue;

                    var paramName = p.Identifier.ValueText;
                    var paramDescAttr = FindAttribute(p.AttributeLists, "Description");
                    var paramDesc = paramDescAttr is null ? "" : ExtractStringArg(paramDescAttr) ?? "";
                    var defaultValue = p.Default?.Value?.ToString();
                    var routerType = MapType(typeText);

                    parameters.Add(new ParameterInfo(paramName, routerType, paramDesc, defaultValue));
                }

                yield return new ToolInfo(className, toolName, description, parameters.ToImmutableArray());
            }
        }
    }

    private static string MapType(string typeText)
    {
        // Normalise whitespace inside the syntactic type. Arrays/nullables come through
        // as `string?`, `string[]`, `double?` etc.
        var t = typeText.Replace(" ", "");
        return PassThroughTypes.Contains(t)
            ? t
            : "global::System.Text.Json.JsonElement?";
    }

    private static void EmitProxy(StringBuilder sb, ToolInfo tool)
    {
        var className = $"{tool.ClassName}Proxy";

        sb.AppendLine("[global::ModelContextProtocol.Server.McpServerToolType]");
        sb.AppendLine($"public class {className}(global::RhMcp.Router.ProxyDispatcher proxy)");
        sb.AppendLine("{");
        sb.AppendLine($"    [global::ModelContextProtocol.Server.McpServerTool(Name = \"{tool.Name}\")]");
        sb.AppendLine($"    [global::System.ComponentModel.Description(\"{EscapeString(tool.Description)}\")]");
        sb.AppendLine($"    public global::System.Threading.Tasks.Task<string> InvokeAsync(");

        // Emit original plugin parameters first (required ones may have no default,
        // optional ones carry their plugin-side default through). `slot` follows as
        // an optional trailing arg — must come after any required param per C# rules.
        foreach (var p in tool.Parameters)
        {
            sb.Append($"        [global::System.ComponentModel.Description(\"{EscapeString(p.Description)}\")] {p.Type} {p.Name}");
            if (p.Default is not null) sb.Append($" = {p.Default}");
            sb.AppendLine(",");
        }

        sb.AppendLine("        [global::System.ComponentModel.Description(\"Slot ID returned by spawn_slot. Omit to use the router's default Rhino (auto-spawned on first slot-less call).\")] string? slot = null,");

        sb.AppendLine("        global::System.Threading.CancellationToken ct = default)");
        sb.AppendLine("    {");

        var argsList = string.Join(", ", tool.Parameters.Select(p => p.Name));
        sb.AppendLine($"        return proxy.CallToolAsync(slot, \"{tool.Name}\", new {{ {argsList} }}, ct);");

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static bool HasAttribute(SyntaxList<AttributeListSyntax> lists, string name)
        => FindAttribute(lists, name) is not null;

    private static AttributeSyntax? FindAttribute(SyntaxList<AttributeListSyntax> lists, string name)
    {
        foreach (var list in lists)
        {
            foreach (var attr in list.Attributes)
            {
                var attrName = attr.Name.ToString();
                // Handle `[McpServerTool]`, `[McpServerToolAttribute]`, `[Foo.McpServerTool]`.
                var lastDot = attrName.LastIndexOf('.');
                if (lastDot >= 0) attrName = attrName.Substring(lastDot + 1);
                if (attrName == name || attrName == name + "Attribute") return attr;
            }
        }
        return null;
    }

    /// <summary>
    /// Extract a string argument from an attribute. If <paramref name="namedArg"/> is supplied,
    /// look for `Name = "value"`; otherwise return the first positional string literal.
    /// </summary>
    private static string? ExtractStringArg(AttributeSyntax attr, string? namedArg = null)
    {
        if (attr.ArgumentList is null) return null;

        foreach (var arg in attr.ArgumentList.Arguments)
        {
            if (namedArg is not null)
            {
                if (arg.NameEquals?.Name.Identifier.ValueText != namedArg) continue;
            }

            if (arg.Expression is LiteralExpressionSyntax lit && lit.IsKind(SyntaxKind.StringLiteralExpression))
            {
                return lit.Token.ValueText;
            }
        }
        return null;
    }

    private static string EscapeString(string s)
    {
        return s
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n");
    }

    private readonly record struct ToolInfo(
        string ClassName,
        string Name,
        string Description,
        ImmutableArray<ParameterInfo> Parameters);

    private readonly record struct ParameterInfo(
        string Name,
        string Type,
        string Description,
        string? Default);
}
